### ISSUE TITLE
Use strict types everywhere

### ISSUE THREAD

**Issue by joshdifabio** [snowio/magento2-data-model#4]
All PHP files should use strict types. I.e. they should begin with:
```php
<?php
declare(strict_types=1);
namespace ...
```

**Comment by alexanderwanyoike** [comment]
See https://github.com/snowio/magento2-data-model/commit/154d4b212de2a578a8da8402ec8b57b11383a506

**Comment by joshdifabio** [comment]
Thanks. Please also do update `SetTrait` and then close this issue.
